border_width = 2
margin = 2
workspace_margin=0
default_border_color = "#060404"
floating_border_color = "#FAD49F"
focused_border_color = "#f2e6df"


col1 = "#B4906D"
col2 = "#D89D74"
col3 = "#847C83"
col4 = "#A79A9C"
col5 = "#E2AE99"
col6 = "#FAD49F"
col7 = "#f2e6df"
col8 = "#a9a19c"
col9 = "#B4906D"
col10 = "#D89D74"
col11 = "#847C83"
col12 = "#A79A9C"
col13 = "#E2AE99"
col14 = "#FAD49F"
col15 = "#f2e6df"



background = "#060404"
foreground = "#f2e6df"
