#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Start apps
sxhkd -c "$SCRIPTPATH"/sxhkd/sxhkdrc &
# nm-applet &
xfce4-power-manager &
numlockx on &
# blueberry-tray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# /usr/lib/xfce4/notifyd/xfce4-notifyd &
# volumeicon &
dunst &
# lxappearance &
# sleep 0.6
# killall lxappearance &
# copyq &
# ec4linux-applet &


# Boot picom
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends -b --config "$SCRIPTPATH"/picom/picom.conf &> /dev/null &
fi

# Set background
# ~/Dotfiles/scripts/set-wallpaper &
$SCRIPTPATH/scripts/wal.sh

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

#mainbar
index=0
monitors=($(polybar -m | sed s/:.*//))
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=${monitors[index]} polybar -c "$SCRIPTPATH"/polybar/polybar.ini $barname &> /dev/null &
  # monitor=${monitors[index]} width=$(( width - 10 )) polybar -c "$SCRIPTPATH"/polybar/polybar.ini $barname &> /dev/null &
  let index=index+1
done
