#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Start apps
# set screen resolution and refresh rate
# xrandr --output eDP1 --mode 1920x1080 --pos 1920x0 --rotate normal --output DP1 --off --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rate 74.99 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off
"$SCRIPTPATH"/scripts/screen.sh

sxhkd -c "$SCRIPTPATH"/sxhkd/sxhkdrc &
# nm-applet &
xfce4-power-manager &
numlockx on &
# blueberry-tray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# /usr/lib/xfce4/notifyd/xfce4-notifyd &
# volumeicon &
dunst &
# lxappearance &
# sleep 0.6
# killall lxappearance &
# copyq &
# ec4linux-applet &
# auto lock
xautolock -time 10 -locker "betterlockscreen -l" -notify 30 -notifier "dunstify  -u critical 'Locking in 30 seconds'" &

# Boot picom
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends -b --config "$SCRIPTPATH"/picom/picom.conf &> /dev/null &
fi

# Set background
# ~/Dotfiles/scripts/set-wallpaper &
$SCRIPTPATH/scripts/wal.sh

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#mainbar
index=0
monitors=($(polybar -m | sed s/:.*//))
echo $monitors
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  echo $barname
  monitor=${monitors[index]} polybar -c "$SCRIPTPATH"/polybar/polybar.ini $barname &> /dev/null &
  echo $monitor
  # monitor=${monitors[index]} width=$(( width - 10 )) polybar -c "$SCRIPTPATH"/polybar/polybar.ini $barname &> /dev/null &
  let index=index+1
done
