#!/bin/bash

function send_notification() {
	volume=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))
	dunstify -a "changevolume" -u low -r 9991 -h int:value:"$volume" "Volume-$1" "Volume: $volume" -t 2000
}

case $1 in
up)
	amixer set Master 10%+
	send_notification $1
	;;
down)
	amixer set Master 10%-
	send_notification $1
	;;
mute)
	amixer -D pulse set Master 1+ toggle
	send_notification $1
esac