#!/usr/bin/env bash

function send_notification() {
	# for pulseaudio
	# volume=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))
	# for pipewire
	volume=$(awk '/front-left:/ { print $5 }' <(pactl list sinks))
	dunstify -a "changevolume" -u low -r 9991 -h int:value:"$volume" "Volume-$1" "Volume: $volume" -t 2000
}

case $1 in
up)
	# amixer set Master 10%+
	pactl set-sink-volume @DEFAULT_SINK@ +10%
	send_notification $1
	;;
down)
	# amixer set Master 10%-
	pactl set-sink-volume @DEFAULT_SINK@ -10%
	send_notification $1
	;;
mute)
	# for pulse audio
	# amixer -D pulse set Master 1+ toggle
	# for pipewire
	# amixer -D pipewire set Master 1+ toggle
	pactl set-sink-mute @DEFAULT_SINK@ toggle
	send_notification $1
esac